package com.aiassistant;

/**
 * Placeholder BuildConfig class to satisfy dependencies during development
 * This will be automatically generated by the Android build process
 */
public final class BuildConfig {
    // App constants
    public static final String APPLICATION_ID = "com.aiassistant";
    public static final String BUILD_TYPE = "debug";
    public static final String FLAVOR = "";
    public static final int VERSION_CODE = 1;
    public static final String VERSION_NAME = "1.0";
    
    // Build configuration
    public static final boolean DEBUG = true;
    public static final String BUILD_TIME = "development";
    
    // Feature flags
    public static final boolean ENABLE_LOGGING = true;
    public static final boolean ENABLE_CRASH_REPORTING = false;
    public static final boolean ENABLE_ANALYTICS = false;
    
    // Deep learning config
    public static final boolean USE_GPU_ACCELERATION = false;
    public static final boolean USE_FULL_PRECISION = true;
    public static final boolean USE_QUANTIZED_MODELS = false;
}
