package com.aiassistant.ai.features.automation;

/**
 * Represents an action generated by the Auto AI system
 */
public class AutoAction {
    
    /**
     * Types of actions
     */
    public enum ActionType {
        SUGGEST, // Just suggest to the user
        EXECUTE  // Automatically execute
    }
    
    private ActionType type;
    private String category;
    private String message;
    
    /**
     * Constructor
     * @param type Action type
     * @param category Action category
     * @param message User-facing message
     */
    public AutoAction(ActionType type, String category, String message) {
        this.type = type;
        this.category = category;
        this.message = message;
    }
    
    /**
     * Get the action type
     * @return Action type
     */
    public ActionType getType() {
        return type;
    }
    
    /**
     * Get the action category
     * @return Action category
     */
    public String getCategory() {
        return category;
    }
    
    /**
     * Get the user-facing message
     * @return Message
     */
    public String getMessage() {
        return message;
    }
}
